### ISSUE TITLE
seprate attachment table

### ISSUE THREAD

**Issue by darth-ali** [caspahouzer/wp-cpt-tables#1]
thank you for this awesome plugin, I wish they add this feature soon to WordPress core, I had some questions regarding this plugin:
Does it affect performance because is not supported in core to read and write posts in a different table?
can I still use regular functions like get post meta?
Is it possible to add attachment support to separate attachments table?

**Comment by caspahouzer** [comment]
Hey @darth-ali 

- Yes, it affects the performance. But in a good way. That's the reason I wrote this. Check out the new version with tables optimizing.
- Yes, you can use all regular functions like `get_post`, `get_postmeta`, `WP_Query`, `$wpdb->query` etc.
- For now, the `attachments` are no custom post types in the understandable way. But I will have a look if it could be possible to make an attachment seperation
